server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mohirdev
    username: mohirdev
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
upload:
  server:
    folder: D:/Mohirdev

api:
  json placeholder: https://jsonplaceholder.typicode.com